### PR TITLE
Upgrade projects to VS2013

### PR DESCRIPTION
**Pull request by jmquigs**

### CODE REVIEW

**Comment by dsyme** [comment]
@jack-pappas - Would you like to @sergey-tihon and myself to try to recruit another maintainer for this project?

@jmquigs - Would you be interested in being a co-maintainer?

**Comment by jmquigs** [comment]
@dsyme, thanks for merging my other PR.  Sure, I would like to be co-maintainer.

**Comment by dsyme** [comment]
Great, you are now a co-owner.

**Comment by dsyme** [comment]
(Closing this as it Is covered by #7 )

**Pull request closed without merging**
