### PR TITLE
Updates paket files.

### PR DESCRIPTION
**Pull request by ChrSteinert**

### CODE REVIEW

**Comment by wallymathieu** [comment]
I've verified that the paket.bootstrapper.exe is [paket.bootstrapper.exe](https://github.com/fsprojects/Paket/releases/tag/5.142.0)

**Comment by ChrSteinert** [comment]
Do you mean the as of 88f7359667? I recon that it is a super old bootstrapper?

**Comment by wallymathieu** [comment]
Question is how to fix the build so that this PR can be merged.

**Comment by ChrSteinert** [comment]
oooooooohh...
sorry for being dense .


I'll take a look at the build.

**Comment by wallymathieu** [comment]
No worries 😃

**Comment by ChrSteinert** [comment]
I don't get, why Travis sais it failed. It seems to have the same output as the last sucessfull build.

**Comment by wallymathieu** [comment]
It looks like it's unable to compile https://api.travis-ci.org/v3/job/345857798/log.txt
```
	/home/travis/build/fsprojects/FSharp.Compatibility/.paket/paket.targets: error : Command 'mono --runtime=v4.0.30319 "/home/travis/build/fsprojects/FSharp.Compatibility/.paket/paket.exe" restore --references-file "/home/travis/build/fsprojects/FSharp.Compatibility/FSharp.Compatibility.Scala/paket.references"' exited with code: 2.
```
note the path ...

**Comment by ChrSteinert** [comment]
Seems like Travsi does not like ne new paket.targets file...

**Comment by wallymathieu** [comment]
If you look at the travis yml file, you can note that it's [using xbuild directly](https://github.com/fsprojects/FSharp.Compatibility/blob/master/.travis.yml). If you look at the output from xbuild : 
```
>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
```
It might be using an old type of build by building that way on travis.

A lot of projects use FAKE. It might be easier to get it to work more reliably. What does @jmquigs and @jack-pappas think about doing something here along those lines?

**Comment by wallymathieu** [comment]
I've added a branch to see how appveyor and travis handles it: https://github.com/fsprojects/FSharp.Compatibility/tree/trying-different-configuration

**Comment by wallymathieu** [comment]
Appveyor succeeds for that configuration, while using msbuild on travis gives the following:
https://travis-ci.org/fsprojects/FSharp.Compatibility/builds/345874761
i.e. there might be some bug when compiling .net 4.0 with msbuild

**Comment by wallymathieu** [comment]
So a solution to appveyor build failure would be to change the appveyor.yml and add restore and build

**Comment by jmquigs** [comment]
@wallymathieu I don't have a strong opinion on build system, if Fake makes the build more reliable, then it is probably worth using it.  Also, the .net 4.0 runtime seems pretty old at this point, is there any downside to using something newer (and would that help this issue?)

**Comment by wallymathieu** [comment]
As far as I can see it's [not supported anymore](https://en.wikipedia.org/wiki/.NET_Framework). I used to target .net 4 in order to be able to run it on mono installations. But nowadays it's way easier to use later versions of .net for mono. Another reason why you might use .net 4 is because you have a specific version of Sharepoint that you target. I don't know how common it is that people are forced to use .net 4.0.

**Comment by jmquigs** [comment]
The appveyor build succeeds if I use VS2015 instead of VS2017.  I suspect the project files need to be upgraded to 2017 for that to work.   Or we could just keep it at 2015 for now.

**Comment by wallymathieu** [comment]
or that the paket.targets file works for vs2015 msbuild

**Pull request closed without merging**
